var dbserver = require("../dao/dbserver")
var emailServer = require('../dao/emailServer')
var signup = require('../server/signUp')
var signin = require('../server/signin')
var search = require('../server/search')
var userdetail = require("../server/userdetail")
var friend = require('../server/friend')
var index = require("../server/index")
var chat = require("../server/chat")
var moments = require("../server/moment")
var group = require("../server/group")
module.exports = function (app) {
    app.get("/test",(req,res)=>{
        dbserver.findUser(res);
    })
    //邮箱测试
    app.post("/email",(req,res)=>{
        var mail = req.body.mail
        emailServer.emailSignUp(mail,res)
        res.send(mail)
    })

    //注册
    app.post("/singup/add",(req,res)=>{
        signup.signUp(req,res)
    })
    //用户是否占用
    app.post("/singup/judge",(req,res)=>{
        signup.judgeValue(req,res)
    })

    //登录
    app.post("/singin/match",(req,res)=>{
        signin.signIn(req,res)
    })
    app.post("/singin/token",(req,res)=>{
        res.send("token通过")
    })

    //搜索
    app.post("/search/user",(req,res)=>{
        search.searchUsre(req,res)
    })
    app.post("/search/isfriend",(req,res)=>{
        search.isFriend(req,res)
    })
    app.post("/search/group",(req,res)=>{
        search.searchGroup(req,res)
    })
    app.post("/search/isingroup",(req,res)=>{
        search.isInGroup(req,res)
    })

    //用户详情
    app.post("/user/detail",(req,res)=>{
        userdetail.userDetail(req,res)
    })
    //群详情
    app.post("/group/detail",(req,res)=>{
        group.groupDetail(req,res)
    })
    //用户修改
    app.post("/user/update",(req,res)=>{
        userdetail.userUpdate(req,res)
    })
    //获取好友昵称
    app.post("/user/getmarkname",(req,res)=>{
        userdetail.getMarkName(req,res)
    })
    //修改好友昵称
    app.post("/user/updatemarkname",(req,res)=>{
        userdetail.updateMarkName(req,res)
    })
    //好友申请
    app.post("/friend/applyfriend",(req,res)=>{
        friend.applyfriend(req,res)
    })
    //修改好友状态
    app.post("/friend/updatefriendstate",(req,res)=>{
        friend.updateFriendState(req,res)
    })
    //删除好友
    app.post("/friend/deletefriend",(req,res)=>{
        friend.deleteFriend(req,res)
    })
    //获取好友
    app.post("/index/getfriend",(req,res)=>{
        index.getFriend(req,res)
    })
    //获取聊天列表
    app.post("/index/chatlist",(req,res)=>{
        index.getchatlist(req,res)
    })
    //首页聊天列表好友状态修改
    app.post("/index/updateIndex",(req,res)=>{
        friend.updateFriendStateIndex(req,res)
    })
    //获取消息
    app.post("/index/getlastmsg",(req,res)=>{
        index.getLastMsg(req,res)
    })
    //获取群最后一条消息
    app.post("/group/getlastgroupmsg",(req,res)=>{
        group.getLastGroupMsg(req,res)
    })
    //获取消息未读数
    app.post("/index/unreadmsg",(req,res)=>{
        index.unreadMsg(req,res)
    })
    //已读未读修改
    app.post("/index/updatemsg",(req,res)=>{
        index.updateMsg(req,res)
    })
    //群已读未读修改
    app.post("/group/updatemsg",(req,res)=>{
        group.updateGroupUnread(req,res)
    })
    //创建群
    app.post("/group/buildgroup",(req,res)=>{
        group.buildgroup(req,res)
    })
    //获取群
    app.post("/index/getgroup",(req,res)=>{
        index.getGroup(req,res)
    })
    //申请入群
    app.post("/group/applygroup",(req,res)=>{
        group.applyToGroup(req,res)
    })
    //群主审批
    app.post("/group/headerapply",(req,res)=>{
        group.headerapply(req,res)
    })
    //群获取消息
    app.post("/index/getgroupmsg",(req,res)=>{
        index.getOneGroupMsg(req,res)
    })
    //获取群成员
    app.post("/group/getgroupuser",(req,res)=>{
        group.getgroupUser(req,res)
    })
    //群已读未读修改
    app.post("/index/updategroupmsg",(req,res)=>{
        index.updateGroupMsg(req,res)
    })
    //退出该群
    app.post("/group/outGroup",(req,res)=>{
        group.outGroup(req,res)
    })
    //解散群
    app.post("/group/deletegroupuser",(req,res)=>{
        group.deleteGroup(req,res)
    })
    //群信息修改
    app.post("/group/GroupUpdate",(req,res)=>{
        group.GroupUpdate(req,res)
    })
    //消息
    app.post("/chat/msg",(req,res)=>{
        chat.msg(req,res)
    })
    //群消息
    app.post("/chat/groupmsg",(req,res)=>{
        chat.groupmsg(req,res)
    })
    //发送朋友圈
    app.post("/moments/msg",(req,res)=>{
        moments.moments(req,res)
    })
    //获取朋友圈动态
    app.post("/moments/getmsg",(req,res)=>{
        moments.getmoments(req,res)
    })
    //删除朋友圈
    app.post("/moments/deleteMoment",(req,res)=>{
        moments.deleteMoment(req,res)
    })
    //点赞
    app.post("/moments/zan",(req,res)=>{
        moments.zan(req,res)
    })
    //评论
    app.post("/moments/comment",(req,res)=>{
        moments.comment(req,res)
    })
    //用户签到
    app.post("/user/qiandao",(req,res)=>{
        userdetail.qiandao(req,res)
    })
    //获取用户签到日期
    app.post("/user/qiandaoDate",(req,res)=>{
        userdetail.qiandaoDate(req,res)
    })
    //用户打地鼠成绩
    app.post("/user/mouse",(req,res)=>{
        userdetail.mouse(req,res)
    })
}